# FIXME: Should this be part of torture-server ?

Snippets.class_eval do
  def api(path)
    %(<a href="#{path}"><i class="fa fa-book" aria-hidden="true"></i> API docs</a>)
  end

  def img(_path)
    raise "Please replace `img` with `vite_image_tag`"
  end

  def code_tabs(name, **options)
    options = {collapse: :meths}.merge(options)

    nav_tabs do |tab|
      tab.(title: "Activity", active: true) do
        code(name, **options)
      end

      tab.(title: "Operation") do
        file = "autogenerated/operation_#{model[:file]}"

        code(name, **options.merge(file: file))
      end
    end # nav_tabs
  end

  # Hack to keep CSS classes used in torture-server and not purge them using purge-css
  # TODO: We should avoid hard coding classes in torture-server
  def _keep_this_css_from_purging
    %(<div class="divider navigation mx-auto d-block bd-callout bd-callout-info tab-content tab-pane nav nav-tabs nav-item fade show active nav-link pink"></div>)
  end
end
